-----BEGIN EC PRIVATE KEY-----
MIIB+gIBAQQw/GikAvOLyip2j884WGq3m3ABk4oADnOyQ37H21yzEa4JgGXhXd84
kuzapEEAiLk2oIIBWzCCAVcCAQEwPAYHKoZIzj0BAQIxAP//////////////////
///////////////////////+/////wAAAAAAAAAA/////zB7BDD/////////////
/////////////////////////////v////8AAAAAAAAAAP////wEMLMxL6fiPufk
mI4Fa+P4LRkYHZxu/oFBEgMUCI9QE4daxlY5jYou0Z0qhcjt0+wq7wMVAKM1kmqj
GaJ6HQCJamdzpIJ6zaxzBGEEqofKIr6LBTeOscce8yCtdG4dO2KLp5uYWfdB4IJU
KjhVAvJdv1UpbDpUXjhydgq3NhfeSpYmLG9dnpi/kpLcKfj0Hb0omhR86doxE7Xw
uMAKYLHOHX6BnXpDHXyQ6g5fAjEA////////////////////////////////x2NN
gfQ3Ld9YGg2ySLCneuzsGWrMxSlzAgEBoWQDYgAE8YTKhpixcQamFMLU+u+e7zCF
VxBpTVFJj/3W95Nbuhsf7Mb2hZioQQ85W7M19vCNDCSzgEY2onCljntGIuSL5Rk/
SWm7hUqBVrYsTX4hv4PKHObc6/2bA1VDY7VkTMZC
-----END EC PRIVATE KEY-----
